language: php

matrix:
    fast_finish: true
    include:
        - php: 7.1

branches:
    only:
        - master

before_install:
    - composer selfupdate

install:
    - composer install

script:
    - vendor/bin/codecept run